# Python 3.9 slim 베이스
FROM python:3.9-slim

# ffmpeg 설치 (pydub 라이브러리 의존성)
RUN apt-get update \
    && apt-get install -y ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# 작업 디렉터리 지정
WORKDIR /app

# 파이썬 패키지 설치
COPY stempo-rhythm/requirements.txt /app/
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# 소스 복사
COPY stempo-rhythm/main.py /app/

# FastAPI 서버를 위한 포트 노출
EXPOSE 5000

# Uvicorn으로 FastAPI 서버 실행
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]
