name: Build Spring Boot with Gradle

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java and Gradlew
        uses: ./.github/actions/setup-java-and-gradlew
        with:
          java-distribution: 'liberica'
          java-version: '21'
          java-package: 'jdk'

      - name: Write Application Configuration
        run: |
          mkdir -p config
          echo "${{ secrets.APPLICATION_YAML }}" | base64 --decode > config/application.yml

      - name: Build with Gradle
        run: ./gradlew assemble --info --parallel
