name: Code Quality and SonarCloud Analysis

on:
  workflow_run:
    workflows: [ "Test Spring Boot with Gradle" ]
    types:
      - completed

jobs:
  code_quality_analysis:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: test-results

      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report

      - name: Setup Java and Gradlew
        uses: ./.github/actions/setup-java-and-gradlew
        with:
          java-distribution: 'liberica'
          java-version: '21'
          java-package: 'jdk'

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest -x test --info

      - name: Run JaCoCo Test Coverage Verification
        run: ./gradlew jacocoTestCoverageVerification -x test -x jacocoTestReport --info

      - name: Run SonarCloud Analysis
        run: ./gradlew sonar --info
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
