name: Setup Common

on:
  workflow_call:
    inputs:
      java-distribution:
        required: true
        type: string
      java-version:
        required: true
        type: string
      java-package:
        required: false
        default: 'jdk'
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}
          java-package: ${{ inputs.java-package }}
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash
