name: CI for Spring Boot with Gradle

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Call Common Setup
        uses: ./.github/workflows/setup-common.yml
        with:
          java-distribution: 'liberica'
          java-version: '21'
          java-package: 'jdk'

      - name: Run tests with Gradle
        run: ./gradlew test -Dspring.profiles.active=test --info --parallel

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/build/reports/tests/test/*'

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Write Application Configuration
        run: |
          mkdir -p config
          echo "${{ secrets.APPLICATION_YAML }}" | base64 --decode > config/application.yml

      - name: Call Common Setup
        uses: ./.github/workflows/setup-common.yml
        with:
          java-distribution: 'liberica'
          java-version: '21'
          java-package: 'jdk'

      - name: Build with Gradle
        run: ./gradlew assemble --info --parallel
